version: "3.7"
services:
        app-1:
                image: callumgoodley/animal-app-1
                build: ./app-1
                environment: 
                          MY_SECRET_KEY: ${MY_SECRET_KEY}
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - app-2
        app-2:
                image: callumgoodley/animal-app-2
                build: ./app-2
                environment:
                          MY_SECRET_KEY: ${MY_SECRET_KEY}
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
        nginx:
                image: nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp

                depends_on: 
                        - app-1
                volumes: 
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
